model_familys:
- llama_2
data_loaders:
- CotLoader
- SentimentClassificationLoader
- HC3HumanLoader
- XsumLoader
data_processors:
- v1AvgHeadSoftMaxSentenceEntropyProcessor
- v1SoftMaxSentenceEntropyProcessor
- v1AvgHeadUnSoftMaxSentenceEntropyProcessor
- v1ColumnAvgHeadSoftMaxSentenceEntropyProcessor
- v1ColumnSoftMaxSentenceEntropyProcessor
- v1ColumnAvgHeadUnSoftMaxSentenceEntropyProcessor
- v1FixedAvgHeadSoftMaxSentenceEntropyProcessor
- v1FixedSoftMaxSentenceEntropyProcessor
- v1FixedAvgHeadUnSoftMaxSentenceEntropyProcessor
- v1ColumnFixedAvgHeadSoftMaxSentenceEntropyProcessor
- v1ColumnFixedSoftMaxSentenceEntropyProcessor
- v1ColumnFixedAvgHeadUnSoftMaxSentenceEntropyProcessor
- AvgHeadSoftMaxTokenEntropyProcessor
- AvgHeadUnSoftMaxTokenEntropyProcessor
- SoftMaxTokenEntropyProcessor