model_familys:
- qwen_1.5
data_loaders:
- CotLoader
- SentimentClassificationLoader
- HC3HumanLoader
- XsumLoader
data_processors:
- v1AvgHeadSoftMaxSentenceEntropyProcessor
- v1SoftMaxSentenceEntropyProcessor
- v1UnSoftMaxSentenceEntropyProcessor
- v1ColumnAvgHeadSoftMaxSentenceEntropyProcessor
- v1ColumnSoftMaxSentenceEntropyProcessor
- v1ColumnUnSoftMaxSentenceEntropyProcessor
- v1FixedAvgHeadSoftMaxSentenceEntropyProcessor
- v1FixedSoftMaxSentenceEntropyProcessor
- v1FixedUnSoftMaxSentenceEntropyProcessor
- v1ColumnFixedAvgHeadSoftMaxSentenceEntropyProcessor
- v1ColumnFixedSoftMaxSentenceEntropyProcessor
- v1ColumnFixedUnSoftMaxSentenceEntropyProcessor
- AvgHeadSoftMaxTokenEntropyProcessor
- SoftMaxTokenEntropyProcessor
- UnSoftMaxTokenEntropyProcessor