model_familys:
- qwen_1
data_loaders:
- SentimentClassificationLoader
- HC3HumanLoader
- XsumLoader
- CotLoader
data_processors:
- AvgHeadMeanEntropyProcessor
- MeanEntropyProcessor
- SentenceEntropySoftMaxProcessor
- SentenceEntropyUnSoftMaxProcessor