model_familys:
- qwen
data_loaders:
- CotLoader
# - SentimentClassificationLoader
# - HC3HumanLoader
# - XsumLoader
data_processors:
- AvgHeadSoftMaxMeanEntropyProcessor
- AvgHeadUnSoftMaxMeanEntropyProcessor
- MeanEntropyProcessor
- SentenceEntropySoftMaxProcessor
- SentenceEntropyUnSoftMaxProcessor